/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131314',
        'surface-dim': '#131314',
        'surface-bright': '#3a393a',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low': '#1c1b1c',
        'surface-container': '#201f20',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        'on-surface': '#e5e2e3',
        'on-surface-variant': '#d4c0d7',
        'inverse-surface': '#e5e2e3',
        'inverse-on-surface': '#313031',
        outline: '#9d8ba0',
        'outline-variant': '#514255',
        'surface-tint': '#ecb2ff',
        primary: '#ecb2ff',
        'on-primary': '#520071',
        'primary-container': '#bd00ff',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#9900cf',
        secondary: '#d3fbff',
        'on-secondary': '#00363a',
        'secondary-container': '#00eefc',
        'on-secondary-container': '#00686f',
        tertiary: '#2ae500',
        'on-tertiary': '#053900',
        'tertiary-container': '#168900',
        'on-tertiary-container': '#ffffff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#131314',
        'on-background': '#e5e2e3',
        battle: {
          bg: '#131314',
          surface: '#1c1b1c',
          card: '#201f20',
          border: '#353436',
          accent: '#ecb2ff',
          accentHover: '#bd00ff',
          neon: '#00eefc',
          neonDim: '#00686f',
          gold: '#fbbf24',
          red: '#ffb4ab',
          green: '#2ae500',
          purple: '#9900cf',
          muted: '#514255',
          text: '#e5e2e3',
          textDim: '#d4c0d7',
        },
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Geist"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      animation: {
        'pulse-fast': 'pulse 0.8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.4s ease-out',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px #ecb2ff, 0 0 10px #ecb2ff' },
          '100%': { boxShadow: '0 0 15px #ecb2ff, 0 0 30px #bd00ff, 0 0 50px #bd00ff' },
        },
      },
    },
  },
  plugins: [],
}
